-- apply changes
create table incident_archive (
  id                            number(19) generated by default as identity (increment by 50) not null,
  check_id                      varchar2(100) not null,
  created_at                    number(19) not null,
  ended_at                      number(19) not null,
  reason                        varchar2(1000) not null,
  status                        number(1) not null,
  version                       number(19) not null,
  constraint pk_incident_archive primary key (id)
);

create table planned_maintenance (
  id                            number(19) generated by default as identity (increment by 50) not null,
  check_id                      varchar2(100) not null,
  starting_at                   number(19) not null,
  ending_at                     number(19) not null,
  reason                        varchar2(1000) not null,
  version                       number(19) not null,
  constraint pk_planned_maintenance primary key (id)
);

create table status_check_result (
  id                            number(19) generated by default as identity (increment by 50) not null,
  check_id                      varchar2(100) not null,
  created_at                    number(19) not null,
  check_duration                number(10) not null,
  status                        number(1) not null,
  version                       number(19) not null,
  constraint pk_status_check_result primary key (id)
);

